import type {
  NativePanelRow,
  NativePanelView,
  NativeProjectRow,
} from "../../../src/board/panel.ts";

export function panelFixture(project: string): NativePanelView {
  const projects: NativeProjectRow[] = [
    {
      repoPath: project,
      name: "tandem",
      current: true,
      offline: false,
      running: 4,
      needsYou: 1,
      status: "4 running · 1 needs you",
      shortcut: "⌘1",
      sessionId: "fixture",
    },
    {
      repoPath: `${project}/tagalog-learning-app`,
      name: "tagalog-learning-app",
      current: false,
      offline: false,
      running: 2,
      needsYou: 1,
      status: "2 running · 1 needs you",
      shortcut: "⌘2",
      sessionId: "fixture-other",
    },
    {
      repoPath: `${project}/music-app`,
      name: "music-app",
      current: false,
      offline: false,
      running: 0,
      needsYou: 0,
      status: "idle · 1 PR ready",
      shortcut: "⌘3",
      sessionId: "fixture-music",
    },
  ];
  const row = (
    key: string,
    title: string,
    state: NativePanelRow["state"],
    stage: string,
    time: string,
    model: string,
    detail: string,
    target: NativePanelRow["target"],
    pullRequest?: NativePanelRow["pullRequest"],
  ): NativePanelRow => ({
    key,
    title,
    state,
    stage,
    time,
    model,
    detail,
    secondary: `${model} · ${detail}`,
    target,
    ...(pullRequest === undefined ? {} : { pullRequest }),
  });
  return {
    header: {
      title: "tandem ▾",
      project,
      projects,
      otherProjectsNeedYou: 1,
      bellCount: 3,
      fiveHourLabel: "5h 62% · 2h 14m",
      fiveHour: {
        provider: "anthropic",
        account: "fixture",
        window: "five-hour",
        label: "5h",
        remainingPercent: 38,
        resetInMs: 8040000,
        fetchedAt: "2030-01-01T12:00:00Z",
      },
    },
    sections: [
      {
        title: "Needs you",
        count: 1,
        rows: [
          row(
            "brief:tern",
            "Approve brief: Tern backend",
            "yellow",
            "brief",
            "2m",
            "opus",
            "waiting for your approval",
            { kind: "brief", requestId: "tern" },
          ),
        ],
      },
      {
        title: "Running",
        count: 4,
        rows: [
          row(
            "task:adapter",
            "Tern backend adapter",
            "blue",
            "fixing",
            "12m",
            "opus",
            "editing tern/adapter.ts",
            { kind: "task", taskId: "adapter" },
          ),
          row(
            "task:snapshot",
            "Board snapshot writer",
            "blue",
            "implementing",
            "6m",
            "sonnet",
            "reading board/snapshot.ts",
            { kind: "task", taskId: "snapshot" },
          ),
          row(
            "task:alerts",
            "Inbox alerts from task events",
            "magenta",
            "in review",
            "21m",
            "sonnet",
            "reviewer reading tests/session",
            { kind: "task", taskId: "alerts" },
          ),
          row(
            "task:width",
            "Fix panel width",
            "red",
            "stuck",
            "34m",
            "opus",
            "same 2 problems twice",
            { kind: "task", taskId: "width" },
          ),
        ],
      },
      {
        title: "Ready",
        count: 2,
        rows: [
          row(
            "task:port",
            "Terminal port refactor",
            "green",
            "ready",
            "52m",
            "opus",
            "waiting on you to publish",
            { kind: "pr", repo: "acme/app", number: 281 },
            {
              repo: "acme/app",
              number: 281,
              url: "https://github.com/acme/app/pull/281",
              draft: true,
            },
          ),
          row(
            "task:keys",
            "Panel keyboard navigation",
            "green",
            "armed",
            "41m",
            "sonnet",
            "merging now",
            { kind: "pr", repo: "acme/app", number: 278 },
            {
              repo: "acme/app",
              number: 278,
              url: "https://github.com/acme/app/pull/278",
              draft: false,
            },
          ),
        ],
      },
      { title: "Recently done", count: 3, rows: [] },
    ],
    footer: "⌘⇧B board · ⌘⇧P PRs · ⌘⇧U usage",
  };
}
